### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by tomasite** [gajus/youtube-player#3]
I have one problem when I try import ```react-youtube``` (https://github.com/troybetz/react-youtube) in my react webapp (created with https://github.com/koistya/react-static-boilerplate) but it looks to be caused by ```youtube-player``` as we can see in the stacktrace:
```
$ npm start
Starting 'render'...
ReferenceError: document is not defined
    at load ([..]/webapp/node_modules/load-script/index.js:3:14)
    at exports.default ([..]/webapp/node_modules/youtube-player/dist/es5/loadYouTubeIframeAPI.js:43:33)
    at Object.<anonymous> ([..]/webapp/node_modules/youtube-player/dist/es5/index.js:41:58)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([..]/webapp/node_modules/react-youtube/dist/YouTube.js:23:22)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
(I already tried to escape the serve side rendering with a canUseDom check but it changes nothing, the error occurs during the import..)

For your information I also opened an issue here: https://github.com/koistya/react-static-boilerplate/issues/66
Thanks in advance for your help!
Thomas

**Comment by dsernst** [comment]
Just to offer @gajus a little more context here, the problem is this library is being called to pre-render a React page in node, where there's no `document` global. You can see more discussion about this at https://github.com/troybetz/react-youtube/issues/55 and https://github.com/koistya/react-static-boilerplate/issues/66.

(The `canUseDOM` check is specific to React)

I hate to say this, @tomasite, but the library throwing is actually https://github.com/eldargab/load-script, another dependency down.

One of these packages in the stack — your application, `react-youtube`,  `youtube-player`, or `load-script` — just needs error handling for the case that `document` is undefined.

**Comment by gajus** [comment]
@dsernst Should work fine now.

**Comment by dsernst** [comment]
Nice, makes sense :+1:
