### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by sylvainlap** [gajus/youtube-player#5]
Hi,

I try to use your module in my es6 code (I use Babel & Webpack).

Here is my index.js:
```
import YouTubePlayer from 'youtube-player';

let player;

player = YouTubePlayer('player');

player.loadVideoById('M7lc1UVf-VE');
```

In my index.html (where I include the bundle.js), I got the `<div id="player"></div>`.

However, in my console, I got this error:
```
Unhandled rejection ReferenceError: global is not defined
    at _bluebird2.default.resolve (http://localhost:3000/bundle.js:13742:21)
    at exports.default (http://localhost:3000/bundle.js:13739:23)
    at exports.default (http://localhost:3000/bundle.js:8079:60)
    at Object.<anonymous> (http://localhost:3000/bundle.js:8020:39)
    at __webpack_require__ (http://localhost:3000/bundle.js:521:30)
    at fn (http://localhost:3000/bundle.js:76:20)
    at Object.<anonymous> (http://localhost:3000/bundle.js:553:19)
    at __webpack_require__ (http://localhost:3000/bundle.js:521:30)
    at http://localhost:3000/bundle.js:544:37
    at http://localhost:3000/bundle.js:547:10
```

Any idea ?

**Comment by gajus** [comment]
Version v3.0.2 released that includes 8c67120bc1f84037fcc64471ea36db02d1f18bdc.

**Comment by piotrkulpinski** [comment]
@gajus This is still an issue due to the same code in one of the dependencies - Sister.

https://github.com/gajus/sister/blob/master/src/sister.js#L61

Console error:
```
Uncaught ReferenceError: global is not defined
    at Object.JgUz (sister.js:57)
    at __webpack_require__ (bootstrap 022bad359af130a2aead:19)
    at Object.amq8 (index.js:9)
    at __webpack_require__ (bootstrap 022bad359af130a2aead:19)
    at Object.b/tu (player.js:2)
    at __webpack_require__ (bootstrap 022bad359af130a2aead:19)
    at Object.Kw8Q (popup.js:1)
    at __webpack_require__ (bootstrap 022bad359af130a2aead:19)
    at Object.g7Pl (app.js:17)
    at __webpack_require__ (bootstrap 022bad359af130a2aead:19)
```

**Comment by gajus** [comment]
https://github.com/gajus/sister/commit/421d87905d847961524487a7e0fc11a47d929f4e
